### ISSUE TITLE
[FEAT] Document Skill ID, etc.

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-docs#24]
### Objective

A skill has a "Skill ID", a "Package Name" (PyPI) and a class name. Document what these are, how the differ, what the standard for naming is in these cases, and common places they are used.

### Initial Implementation Requirements

- Define different strings associated with a skill
- Define common configuration values that reference skills and how

### Other Considerations

https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz:matrix.org/$Zl4YAtsUce6NJm3Kz8fVeMHATFFQrR1DZIMB7eFWncg?via=matrix.org&via=nitro.chat&via=tomesh.net

**Comment by strugee** [comment]
@NeonDaniel I believe this can be closed/
